### ISSUE TITLE
#1 Задачи от наставника: Github и Travis

### ISSUE THREAD

**Issue by nirudef** [glokzs/as_crm#1]
Наставник говорит: План на завтра: GitHub, travis-ci.org читаем https://m.habr.com/post/106912/

Конечный результат (суть задачи): 
Github - регистрируемся, изучаем основы. 
Трэвис - настройка .travis.yml файла.

План решения: 
Читаем документацию.

Мотивация: необходимо использовать 
механизм взаимодействия и командной работы над кодом, исключить возможные проблемы в дальнейшем при слиянии кода.

Критерии приемки: 
Пулим (клонируем) тестовый репозиторий, вносящий какие-то изменения и пушим назад в репо. 
Смотрим результат. Определяем правила пула и пуша репозитория, названия веток.

Планируемое время работы: до 
22 часов сего дня!

**Comment by yuraefremov** [comment]
Тикет решен после  автоматической поставки  в продакшен.
