### ISSUE TITLE
Исправление договора  ,  и корневой  страницы.

### ISSUE THREAD

**Issue by yuraefremov** [glokzs/as_crm#116]
Конечный результат:
Отображение договора , т.к рекомендовал заказщик. 
Корневая таблица всех пользователей а не только студентов.
План решения:убрать  слова список студентов, добавить метод который выводит не только студентов, а всех пользователей.
Мотивация:
 Отображение договора согласно требованиям заказчика. Коренвая страница  должна отображать всех пользователей.
Критерий приемки: Отображение всех пользователей которые  существуют в проэкте.  Отображение  всего договора. возможность его  изменить.

**Comment by Aseliya** [comment]
Планируемое время работы: 1час.

**Comment by Aseliya** [comment]
**Затраченное время**: 30 минут.
