### ISSUE TITLE
Доработка страницы Программа курса-Тема

### ISSUE THREAD

**Issue by elenanikiforova30031979** [glokzs/as_crm#118]
**Конечный результат:**
вывод на  странице Программа курса двух вкладок(таб): Раздаточный материал и Домашнее задание
**План решения:**
К сущности Theme необходимо будет добавить поле t.text :content, в котором будет храниться весь текст раздаточного материала.
Во вьюхе http://localhost:3000/admin/themes создать две вкладки Раздаточный материал и Домашнее задание, заполнить минимальным контентом. Для редактирование контента раздатки и домашки необходимо реализовать WISIWIIG.
**Мотивация:**
Требование заказчика: желает в теме курса вкладки.

**Критерий приемки:**
Проверка наличия во вкладке Программа курса - Название темы двух вкладок Раздаточный материал и Домашнее задание.

**Comment by Aseliya** [comment]
Необходимо добавить к сущности Занятия(Lessons) поля "Домашнее задание" и "Дата дедлайна". Соответственно, во всех вьюшках сущности Занятия сделать правки по добавлению поля Домашнее задание.Прописать в сидах формирование домашки.

**Comment by elenanikiforova30031979** [comment]
планируемое время выполнения 1 час

**Comment by Aseliya** [comment]
Планируемое время: 40 минут.

**Comment by Aseliya** [comment]
затраченное время: 40 минут.
