### ISSUE TITLE
Доработка личного кабинета Студента

### ISSUE THREAD

**Issue by Aseliya** [glokzs/as_crm#123]
**Конечный результат:**
Вывод в личном кабинете студента:
Возможность редактировать: телефон, аватар студенту. 
Возможность загружать готовые домашние работы с личного кабинета, соответственно номеру Занятия.
**План решения:**
Во вьюхе students/show и students/edit сделать правки кода, соответственно требованиям тикета.
**Мотивация:**
Требование заказчика.
**Критерий приемки:**
В кабинете студента есть возможность редактировать пароль, телефон, аватар.
Реализована возможность отправки готовых домашних работ.(Использовать ActiveStorage)

**Comment by yuraefremov** [comment]
4 дня

**Comment by yuraefremov** [comment]
2 дня
