### ISSUE TITLE
Доработка вкладки Занятия

### ISSUE THREAD

**Issue by Aseliya** [glokzs/as_crm#124]
**Конечный результат:**
Вывод во вкладке Группы-Занятия полей: Номер занятия, Тема занятия, Дата занятия, Домашнее задание(чекбокс - есть домашка или нет на данное занятие), Дата дедлайна, Действия
**План решения:**
Во вьюхе http://localhost:3000/admin/groups/show сделать правки кода, соответственно требованиям тикета.
**Мотивация:**
Требование заказчика.
**Критерий приемки:**
Во вкладке Группы-Занятия  должны быть поля: Номер занятия, Тема занятия, Дата занятия, Домашнее задание(Есть домашка, Нет домашки на данное занятие), Дата дедлайна, Действия

**Comment by elenanikiforova30031979** [comment]
примерное время работы 2 часа

**Comment by Aseliya** [comment]
Затраченное время: 10 минут.
