### ISSUE TITLE
Изменения и добавления в кабинете студента . Доработка тикета 123

### ISSUE THREAD

**Issue by yuraefremov** [glokzs/as_crm#134]
**Конечный результат:**  Вы вод в шоу  раздатку  темы урока, и раздатку домашнего задания
**План решения:**
Во вьюхе http://localhost:3000/admin/groups/show сделать правки кода, соответственно требованиям тикета.
**Мотивация:**
Отображение  раздаток  студенту.
**Критерий приемки:**
При в ходе  на страницу студента  , при линке переходим на раздатку домашки и раздатки урока.

**Comment by Aseliya** [comment]
**Планируемое время:** 40 минут.

**Comment by Aseliya** [comment]
**Затраченное время:** 40 минут.

**Comment by yuraefremov** [comment]
Закрыт . все по нему сделали
