### ISSUE TITLE
Добавление сущности Рецензии

### ISSUE THREAD

**Issue by yuraefremov** [glokzs/as_crm#137]
**Конечный результат:**
Создание сущности Рецензии и возможность создания   рецензии с выставлением оценки за домашку. 
Вывод на странице группы, вкладки рецензии при клике на которую выводится список студентов группы . Над списком должно выводится название  строк (ФИО, рецензия, оценка, кнопка "опубликовать" .Над названием строк  должно выводится :Рецензия на занятие(название занятия). Над Названием занятия должно выходить навигационное меню Группы. 
Напротив фамилии каждого студента выходит ссылка"создать рецензию" (если рецензия уже создана ссылка должна быть "редактировать рецензию"), вывод оценки за рецензию.
**План решения:**
- Создать  сущность рецензий   Связать ее  cо студентом. У сущности должны  быть  title,  content,  homework_id,  дата рецензии, rate(оценка.)
- Внести изменения в кода вьюхи admin/group/show
**Мотивация:**
Требованиезаказчика
**Критерий приемки:**
Вывод на странице группы, вкладки рецензии при клике на которую выводится список студентов группы . Над списком должно выводится название  строк (ФИО, рецензия, оценка, кнопка "опубликовать" .Над названием строк  должно выводится :Рецензия на занятие(название занятия). Над Названием занятия должно выходить навигационное меню Группы. 
Напротив фамилии каждого студента выходит ссылка"создать рецензию" (если рецензия уже создана ссылка должна быть "редактировать рецензию"), вывод оценки за рецензию.

**Comment by Aseliya** [comment]
**Примерное время работы:** 2 часа.

**Comment by Aseliya** [comment]
Необходимы уточнения у Заказчика: где и как будет отражаться сам шаблон Рецензии.

**Comment by Aseliya** [comment]
**В связи с дополнениями Заказчика, планируемое время работы:** 5 часов.
На создание сущности и вывода во вьюхе **затрачено**: 4 часа. Т.к. возникли сложности в сборе коллекции сущностей, необходимо было продумать вариант вывода Рецензии, т.к. в тикете не было указано место вывода.

**Comment by Aseliya** [comment]
В процессе вывода рецензий возникла необходимость связать Рецензии(review) с занятием(lesson).

**Comment by Aseliya** [comment]
**Затраченное время:** 12 часов. Возникли трудности с выводом рецензий у полученных домашек соответственно теме урока. В процессе реализации тикет 137 и тикет 142 объединила, т.к. оба тикета касаются одной сущности - Рецензии.
