### ISSUE TITLE
Написание рецензии и выставление оценки

### ISSUE THREAD

**Issue by elenanikiforova30031979** [glokzs/as_crm#142]
**Конечный результат:**
Возможность написания рецензии (текстовый редактор WYSIWYG) на каждого студента по домашкам и выставление оценки
**План решения:**
* Во вьюхе admin/groups/show во вкладке Рецензии   сделать правки кода, соответственно требованиям тикета.
Установить под темой ссылку на редактирование  admin/review/1/edit.
  **Мотивация:**
  Требование заказчика
  **Критерий приемки:**
  При клике на кнопку "создание рецензии" студента должна выходить страничка для редактирования и создания рецензии, сверху на странице должны выходить все закладки , как на странице группы, Ниже должно выходить : Рецензия, ФИО студента, название занятие.
ниже поле для выставления оценки, далее текстовый редактор WYSIWYG с возможность добавления видео

**Comment by Aseliya** [comment]
**Планируемое время:** 2 часа.

**Comment by Aseliya** [comment]
**Затраченное время:** 30 минут. Гем для редактора был установлен ранее. Требовалось только присвоить класс полю, в котором необходим данный редактор.
