### ISSUE TITLE
Доработка профиля студента

### ISSUE THREAD

**Issue by elenanikiforova30031979** [glokzs/as_crm#144]
**Конечный результат:**
В профиле студента (при просмотре студентом)  должно быть навигационное меню с вкладками:
Домашки, Успеваемость, Занятия, Мой профиль (при клике на мой профиль долны выходить все регистрационные данные студента)
  
**План решения:**
 в кода вьюхи students/show
  **Мотивация:**
  Требование заказчика
  **Критерий приемки:**
   В профиле студента (при просмотре студентом)  должно быть навигационное меню с вкладками:
Домашки, Успеваемость, Занятия, Мой профиль (при клике на мой профиль долны выходить все регистрационные данные студента)

**Comment by Aseliya** [comment]
**Доработать**: содержимое вкладки Мой профиль перенести в навбар пользователя. Там же закрепить аватар(зафиксировать высоту аватарки, чтобы поля не выходили за грани навбара независимо от размера, загружаемого аватара), который будет служить ссылкой на профиль пользователя.
