### ISSUE TITLE
Наполнение seed файла для проверки приложения

### ISSUE THREAD

**Issue by Aseliya** [glokzs/as_crm#150]
**Конечный результат:**
Файл Seed.rb заполнить: Студенты - 10-12 ед., Группы - 5 ед., Курсы - 3 ед., Преподаватели - 2 ед., Темы занятий(Theme) - 10 ед.(закрепить к разным группам), занятия(Lesson) - 15-20 ед.(закрепить к разным группам, к разным занятиям),  Домашки - 10 ед.(к разным студентам на разные темы), Рецензии - 5-7 ед.(к разным темам на разные домашки).
**План решения:**
Произвести соответствующие правки кода в seed.rb.
**Мотивация:**
Требование заказчика для проверки корректной работы приложения. 
Необходимость для разработчиков, дающая возможность протестировать приложение, варьируя данными.
**Критерий приемки:**
Заполненный seed файл.

**Comment by elenanikiforova30031979** [comment]
планируемое время 30 мин

**Comment by elenanikiforova30031979** [comment]
время выполнения 3 часа
