### ISSUE TITLE
Редактирование страницы Root

### ISSUE THREAD

**Issue by Aseliya** [glokzs/as_crm#151]
**Конечный результат:**
Список всех пользователей на главной странице, без генерации договора для студентов.

**План решения:**
Убрать в колонке Действия генерацию договоров для студентов.
**Мотивация:**
Требование заказчика.
**Критерий приемки:**
Полный список всех пользователей приложения на главной странице.

**Comment by elenanikiforova30031979** [comment]
планируемое время работ 30 мин

**Comment by elenanikiforova30031979** [comment]
время работы 15 мин
