### ISSUE TITLE
Доработка вкладки Домашние задания в Админ панели

### ISSUE THREAD

**Issue by Aseliya** [glokzs/as_crm#154]
**Конечный результат:**
Проходим по ссылке http://localhost:3000/admin/lessons/1/homeworks(Группа(1), вкладка Домашние задания). ФИО всех студентов ГРУППЫ, напротив **Cтатус** по домашке (если получена домашка от данного студента - **галочка**, нет - **пробел**), **Рецензия** - Создать/Редактировать/Посмотреть, **Оценка за домашку**
**План решения:**
Внести соответствующие правки кода во вьюхи. Связь между сущностями была проложена ранее.
**Мотивация:**
Требование заказчика
**Критерий приемки:**
Отсутствие в меню таб вкладки Рецензии. Перенос содержимого данной вкладки во вкладку домашние задания.

**Comment by yuraefremov** [comment]
2 дня

**Comment by Aseliya** [comment]
Данный тикет не актуален, т.к. в период его решения Заказчик изменил требования. 
Актуальные требования Заказчика не соответствуют данному тикету.

**Comment by Aseliya** [comment]
Списка всех студентов определенной группы не требуется. Выводятся только ФИО тех студентов, которые сдали домашние работы.
