### ISSUE TITLE
Доработка первоначальной загрузочной страници Студента

### ISSUE THREAD

**Issue by yuraefremov** [glokzs/as_crm#162]
Конечный результат:  При  выводе вкладки занятия  должны выводиться только те темы  которые соответствуют данной группе  где находится студент. Во вкладке видео нужно  добавить  наличие  видео урока или его отсутствие  (фонт осом 'камера").
План решения:
Внести соответствующие правки кода во вьюхи. Связь между сущностями была проложена ранее.
Мотивация:
Требование заказчика
Критерий приемки:  зайти под студентом  проверить  .

**Comment by Aseliya** [comment]
**Планируемое время работы над тикетом:** 1 час.

**Comment by Aseliya** [comment]
**Затраченное время:** 2 часа.  Необходимо было перестроить зависимости сущсностей. Потребовалась доработка сущности Рецензии для их отражения во вкладке Рецензии в кабинете студента.

**Comment by Aseliya** [comment]
Необходима доработка по полю Видео к уроку, т.к. видео представляют из себя ссылки, закрпеляемые через текстовый редактор WYSYWIG. Дополнительно потребуется решение: присвоить допполе к Занятию или же каким то образом из редактора "вытаскивать" поле со ссылкой.
**Планируемое доп. время:** 1 час.

**Comment by Aseliya** [comment]
**Затраченное время: 2 часа.** Потребовалась перенастройка гема font-awesome , т.к. гем не отражал иконки с двойным названием(например far fa-camera).
