### ISSUE TITLE
Кнопка для получени я домашней работы от студента после дедлайна.

### ISSUE THREAD

**Issue by yuraefremov** [glokzs/as_crm#164]
Конечный результат: Создание  кнопки включения принятия домашнего задания,от студента,  после дедлайна. 
План решения:
Кнопку  нужно перенести  на  начальную страницу Преподавателя. Кнока должна быть большая  ( ее должно быть видно хорошо) Кнопка должна находиться  в верхнем правом углу  под нав баром.  
Мотивация:
Требование заказчика ( Студент получает разрешение от преподователя для загрузки домашки Препод выключает  кнопку. )
 
Критерий приемки: зайти под студентом отправить  домашнее задание до дедлайна  и после дедлайна выключив при этом кнопку

**Comment by Aseliya** [comment]
Считаю что необходимо объединить тикет 170 и тикет 164, т.к. для реализации approve кнопки для преподавателя необходимо реализовать вообще само получение домашки преподавателем от студента.

**Comment by Aseliya** [comment]
**Планируемое время:** 1 день.

**Comment by Aseliya** [comment]
**Общее затраченное время:** 7 дней. При реализации данного тикета возникла необходимость отрефакторить сущности Рецензии, Домашние работы, наполнить сид файл данными. В данный тикет были вложены решения тикета №154(обоснование: для того, чтобы не нарушить целостность работы зависимых сущностей), тикет №124(обоснование: тикет дорабатывался 1 месяц, соответственно, требовалось вывести требования по данному тикету в приложение), тикет 170(обоснование: возможность скачивать домашки дала возможность запрещать/разрешать отсылку след. домашки студенту).
