### ISSUE TITLE
Рассылка с помощью емаил

### ISSUE THREAD

**Issue by yuraefremov** [glokzs/as_crm#167]
Конечный результат:  Реализовать  в проект рассылку по емаил.
План решения:
 Замена гема Letter_opener .... Выпилить из проэкта гем . заменить его сервесом рассылок  компании Атрактор скул.
Мотивация: Требование заказчика
Критерий приемки:  При создании нового студента или преподователя присылается письмо с изменением пароля, на вход.

**Comment by elenanikiforova30031979** [comment]
Примерное время работы 3 часа

**Comment by yuraefremov** [comment]
сделаю его  за 1 день

**Comment by yuraefremov** [comment]
Читал документацию  2 дня. добавил  в www/config/environments/production.rb  такой код: ActionMailer::Base.smtp_settings = {
    :address              => 'smtp.yandex.ru',
    :domain               => 'yandex.ru',
    :port                 => 465,
    :user_name            => "test@yandex.kz",
    :password             => "123456",
    :authentication       => 'plain',
    :enable_starttls_auto => true,
    :tls                  => true
  }

**Comment by yuraefremov** [comment]
добавил еще в www/config/environments/production.rb   строку  config.action_mailer.default_url_options = { :host => ‘url_or_ip’ }

**Comment by yuraefremov** [comment]
добавил   в www/config/environments/production.rb  код
config.action_mailer.delivery_method = :smtp 
  config.action_mailer.perform_deliveries = true
  config.action_mailer.default_options = { from: 'моя почта' }

 а initialize/devise.rb добавил
config.mailer_sender = "моя почта"

**Comment by yuraefremov** [comment]
изменил  в www/config/environments/production.rb  код
 ActionMailer::Base.smtp_settings = {
    :address              => 'smtp.yandex.kz',
    :domain               => 'yandex.kz',
    :port                 => 465,
    :user_name            => 'efremov18228@yandex.kz',
    :password             => 'yura18228',
    :authentication       => 'plain',
    :enable_starttls_auto => true,
    :tls                  => true
  }

**Comment by yuraefremov** [comment]
сделал за 2дня

**Comment by yuraefremov** [comment]
Сделал  отсылку по  емаилу  прямо в продакшене. ветка  167  не нужна. можно убрать.
