### ISSUE TITLE
Скачивание домашней работы

### ISSUE THREAD

**Issue by yuraefremov** [glokzs/as_crm#170]
**Конечный результат:**
Архивный файл домашки, закрепленный студентом к отправляемому письму ДЗ должен скачиваться через админ панель. Ссылку настроить напротив ФИО каждого студента, сдавшего домашку.
**План решения:**
Внести соответствующие правки кода во вьюхи 
**Мотивация:**
Требование заказчика.
**Критерий приемки:**
При нажатии на ссылку загрузки домашки происходит скачивание файла домашки на локальный компьютер.

**Comment by Aseliya** [comment]
**Затраченное время:** 2 дня.
