### ISSUE TITLE
Создание тестов

### ISSUE THREAD

**Issue by yuraefremov** [glokzs/as_crm#177]
Конечный результат: Тесты  создание  на студента , преподавателя.
План решения:
при помощи гемов cucumber создать тест на создание пользователей студент,преподаватель
Мотивация:
через раз не создается  студент

Критерий приемки:
Тест должен проходить в зеленую стадию

**Comment by Aseliya** [comment]
Планируемое время: 1 день.

**Comment by Aseliya** [comment]
**Затраченное время:** 1 день. (в совокупности)
