### ISSUE TITLE
Написание тестов на сущности Тема курса, Занятие

### ISSUE THREAD

**Issue by Aseliya** [glokzs/as_crm#183]
**Конечный результат:** 
Тесты создания и редактирования сущностей Тема курса и Занятие.
**План решения:**
Написать сценарий на создание и редактирование Темы курса и Занятия, соответственно сценария написать логику прохождения теста.
**Мотивация:**
Необходимость проверки корректной работы приложения в областях Тема курса и Занятие.

**Критерий приемки:**
Тест должен проходить в зеленую стадию

**Comment by yuraefremov** [comment]
Выполню за 3 дня

**Comment by yuraefremov** [comment]
сделал за 2 дня
