### ISSUE TITLE
Наполнение контентом приложения в Production

### ISSUE THREAD

**Issue by Aseliya** [glokzs/as_crm#184]
**Конечный результат:** 
На боевом сервере приложение должно быть наполнено контентом.
**План решения:**
Создать 10 студентов(паре студентов присвоить фотографии для наглядности, остальным оставить default), 2-3 курса, 1-2 преподавателя. 
**Мотивация:**
Контент необходим для демонстрации работы приложения.
**Критерий приемки:**
Приложение в продакшн, наполненное контентом (приложить скриншот с продакшн о проделанной работе)

**Comment by yuraefremov** [comment]
за 1 день

**Comment by yuraefremov** [comment]
сделал за 1день

**Comment by Aseliya** [comment]
![image](https://user-images.githubusercontent.com/46473661/55474538-38eeb680-5633-11e9-801a-c2c5aa2557ad.png)
