### ISSUE TITLE
Доработка вьюхи show/students/admin

### ISSUE THREAD

**Issue by elenanikiforova30031979** [glokzs/as_crm#88]
Конечный результат:
Профиль студента для админа должен содержать поля фото удостоверения личности с двух сторон и  всю информацию о студенте.

План решения:
Во вьюхе admin/students/show.html.erb необходимо сделать правки кода. Расположить по правому краю фото двух сторон удостоверения(использовать Active Storage). В контроллере студента "разрешить" поля фото, в модели студента прописать хелперы (has_many_foto), во вьюхе обозначить что поле фото может принимать несколько файлов (multiple).
Мотивация:
исправить ошибку pull reqest # 54  тикета
Критерий приемки:
Проверка наличия фотографии удостоверения личности в профиле студента через админ панель и всей информации в профиле студента через админ панель.

**Comment by Aseliya** [comment]
Фотографии удостоверения должны быть в уменьшенном вариант и увеличиваться при клике. 
Так же прошу прописать в seed файле метод подгрузки удостоверения и аватарки,т.к. при каждом слиянии тикета НАДО!!! БД очищать!

**Comment by yuraefremov** [comment]
думаю сделаю его за 40 мин

**Comment by Aseliya** [comment]
Юрий, доработайте! Поля удостоверения личности необходимо сделать всплывающими! Вот вам источники: https://lokeshdhakar.com/projects/lightbox2/#examples , https://www.youtube.com/watch?v=GtuIbVdoN_I   исчерпывающие.

**Comment by Aseliya** [comment]
В коде bug. 
Шаги воспроизведения:
Захожу на главную страницу, регистрируюсь со сменой пароля как студент, загружаю свою аватарку.
Наблюдаемое поведение:
При сохранении фото меня редиректит на главную страницу. Аватарку загрузить так и не удалось!
Ожидаемое поведение:
Сохранение аватарки и корректный редирект на профиль студента с загруженной аватаркой.
Причины:
Нет метода update в контроллере с редиректом, хотя во вьюхе кнопки для изменения указаны.
Вариант решения:
Дописать action.

**Comment by Aseliya** [comment]
Одна кнопка Изменить для двух полей Аватар и Удостоверение личности не пойдет.

**Comment by Aseliya** [comment]
![image](https://user-images.githubusercontent.com/46473661/51822612-1379bf80-2307-11e9-9825-d0bfacd0a13a.png)


**Конечный результат:** 
Страница студента в админке должна выглядеть согласно утвержденному мокапу Заказчика.

**Comment by yuraefremov** [comment]
При решении возникли проблемы. Утвержден другой мок ап заказчиком.

**Comment by yuraefremov** [comment]
Доработака  тикета  согластно  требованиямЗказчика: Во вкладке admin\student\show и в student\show изменить иконки фонт осома на (ИНН, Кем выдан, Дача выдачи, Удостоверение №) Во вкладке admin\student\show убрать все кнопки для добавления аватарки, и сканом удостоверения. Кнопки должны находится в admin\student\edit . На изменение или добавление или удаление аватарки и сканов. Во вкладке student\show сделать одну кнопку в низу для изменения аватарки, добавления ее или удаления ее. В admin\student\show и в student\show убрать кнопку “Back” В admin\student\edit должно быть не только добавление сканов и аватарки, но и изменение, и удаление их. Во вкладке admin\student\edit заказчик хочет в поле установки даты, при нажатии на любое число, будь то будет дата, месяц или год должен выходить календарь. Во вкладке редактирования при добавлении аватарки и сканом пользователь также должен остаться во вкладке редактирования, кладка при изменении не должна измениться ка какую либо другую. Изменить название кнопки для изменений на другое более подходящее. В модальном окне картинка сканов должна попадать во всплывающую область модального окна (сделать авто, вид 100% фото или ресайз на фронтенде) При выполнении кнопки для добавления сканов и аватарки. Нужно, что бы при простом нажатии кнопки программа не падала. Если нет аватарки, должно быть отображено пустое место в виде стандартной дефолтной иконки “ Контур профиля человека на сером фоне” Поменять шрифт admin\student\show на Ариал что бы весь проект был в одном стиле. Во вкладке редактирования студента в admin\student\edit поля студента укоротить от правого края на одну треть части. В кладке просмотра студентов и создания договора. Вместо номера (цифры) договора сделать “Посмотреть договор”, или сделать иконку фонт осома в виде глаза.
