### ISSUE TITLE
Тестирование( BDD) с использованием Rspec

### ISSUE THREAD

**Issue by Aseliya** [glokzs/as_crm#94]
**Конечный результат:**
Настройка и подключение гема rspec

**План решения:**
Настроить гем rspec, разобраться в документации.

**Мотивация:**
Рекомендация наставника. Тесты необходимы для проверки корректности работы кода при каких либо его изменениях.

**Критерий приемки:**
Настроенный гем.

**Comment by elenanikiforova30031979** [comment]
Тикет закрывается в связи началом новой разработкой БДД

**Comment by Aseliya** [comment]
При решении данного тикета возникли проблемы с сидами, требуется дополнительная установка гема factory_bot
