### ISSUE TITLE
Создание модели Домашки

### ISSUE THREAD

**Issue by elenanikiforova30031979** [glokzs/as_crm#96]
Конечный результат:
Создать модель Homework

План решения:
Генерируем модель Homework с полями
lesson_id:integer
date:date (это будет дата сдачи домашки)
student_id:integer
 
Устанавливаем связь с моделью Group
делаем CRUD для Админа
Создаем контроллер admin/homeworks_controller
Создаем вьюхи admin(index, show, edit, update, delete)
Настраиваем роутинг для админа

Мотивация:
необходимость просмотра наличия Домашек у студентов определенной группы

Критерий приемки:
Проверка таблицы, создание занятий, проверка наличия домашки

**Comment by Aseliya** [comment]
Планируемое время работы: 1 час

**Comment by Aseliya** [comment]
Затраченное время: 3 часа. Необходимо было параллельно решить тикет 100, т.к. не представлялось возможным собрать коллекцию и вывести необходимую информацию на странице домашек.
