### ISSUE TITLE
Вывод списка студентов определенной группы 

### ISSUE THREAD

**Issue by elenanikiforova30031979** [glokzs/as_crm#97]
Конечный результат:
При клике на определенную группу должен выходить список студентов этой Группы (например Ruby on Rails) с их данными : ФИ, телефон1, телефон2, email, telegram
План решения:
 необходимо сделать правки кода вьюхи: admin/groups/show  
 
Мотивация:
Студента необходимо закрепить к определенной группе  и проверить его наличие   в группе
Критерий приемки:
Проверка наличия   списка студентов определенной  группы

**Comment by elenanikiforova30031979** [comment]
примерное время выполнения  30 мин

**Comment by Aseliya** [comment]
Тикет закрыт ввиду не актуальности решения данного вопроса.
