### ISSUE TITLE
Добавление гема RuboCop, 

### ISSUE THREAD

**Issue by elenanikiforova30031979** [glokzs/as_crm#98]
Конечный результат: 
Установка гема  RuboCop

План решения:
 Как установить и настроить гем  RuboCop можно воспользоваться  следующими ссылками:
https://docs.rubocop.org/en/latest/installation/,  https://blog.sideci.com/use-rubocop-to-check-the-conformity-of-your-ruby-code-with-the-style-guide-6a5bef9bf1e0

  
Мотивация: Возможность автоматически проверять или форматировать  код  
Критерий приемки:
Наличие гема RuboCop

**Comment by yuraefremov** [comment]
24 часа
